name: EnsureUI Tests

on:
  push:
    branches: main

jobs:
 ensure-ui-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run EnsureUI Tests
        uses: dima-kov/ensure-ui@main
        with:
          deployment-url: "transitivebullsh.it"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ensure-ui-screenshots
          path: screenshots/
          retention-days: 7
